import { designStatus } from '#architecture/component-model.mjs'

export const viewerComponents = [
  {
    id: 'viewer-state-data',
    responsibility: 'Own browser state, graph loading, filtering, labels, and shared UI utilities.',
    role: 'adapter',
    files: [
      'viewer/graph-gateway.mjs',
      'viewer/viewer-elements.js',
      'viewer/viewer-state.js',
      'viewer/viewer-store.mjs',
      'viewer/viewer-data.js',
      'viewer/viewer-data-context.js',
      'viewer/viewer-filter-controls.js',
      'viewer/viewer-filter-initialization.js',
      'viewer/viewer-filters.js',
      'viewer/viewer-health.js',
      'viewer/viewer-operation-contract.mjs',
      'viewer/viewer-project-map-presentation.js',
      'viewer/viewer-report-model.js',
      'viewer/viewer-report-renderer.js',
      'viewer/viewer-utils.js'
    ],
    contracts: ['ViewerStore', 'GraphGateway', 'ViewerOperationContract'],
    compositionRoot: false,
    design: designStatus('pass', 'pass', 'pass', 'pass', 'pass'),
    decision: 'Keep state store-owned and route browser effects through explicitly configured module boundaries.'
  },
  {
    id: 'viewer-trace',
    responsibility: 'Calculate execution traces and trace-focused layouts.',
    role: 'core',
    files: [
      'viewer/trace-strategy.mjs',
      'viewer/viewer-trace.js',
      'viewer/viewer-trace-context.js',
      'viewer/viewer-trace-layout.js',
      'viewer/viewer-trace-module.js',
      'viewer/viewer-trace-policy.js',
      'viewer/viewer-trace-reachability.js',
      'viewer/viewer-trace-search.js',
      'viewer/viewer-trace-system.js'
    ],
    contracts: ['TraceStrategy'],
    compositionRoot: false,
    design: designStatus('pass', 'pass', 'pass', 'pass', 'pass'),
    decision: 'Keep trace calculation pure by passing graph data, visible nodes, labels, and view mode explicitly.'
  },
  {
    id: 'viewer-rendering',
    responsibility: 'Lay out graph views and render graph primitives as SVG.',
    role: 'adapter',
    files: [
      'viewer/rendering-contracts.mjs',
      'viewer/viewer-graph.js',
      'viewer/viewer-layout-circular.js',
      'viewer/viewer-layout-domain.js',
      'viewer/viewer-layout-domain-clusters.js',
      'viewer/viewer-layout-domain-collisions.js',
      'viewer/viewer-layout-domain-force.js',
      'viewer/viewer-layout-domain-grid.js',
      'viewer/viewer-layout-domain-order.js',
      'viewer/viewer-layout-layered.js',
      'viewer/viewer-layout-layered-levels.js',
      'viewer/viewer-layout-layered-policy.js',
      'viewer/viewer-layout-system.js',
      'viewer/viewer-layouts.js',
      'viewer/viewer-render-domain.js',
      'viewer/viewer-render-focus.js',
      'viewer/viewer-render-graph.js',
      'viewer/viewer-render-system.js',
      'viewer/viewer-rendering-strategies.js',
      'viewer/viewer-svg.js',
      'viewer/viewer-svg-edges.js',
      'viewer/viewer-svg-nodes.js',
      'viewer/viewer-svg-system.js'
    ],
    contracts: ['LayoutStrategy', 'NodeRenderer', 'EdgeRenderer'],
    compositionRoot: false,
    design: designStatus('pass', 'pass', 'pass', 'pass', 'pass'),
    decision: 'Keep view coordination, layout algorithms, and SVG primitives in focused registered modules.'
  },
  {
    id: 'viewer-ui',
    responsibility: 'Coordinate browser interactions and render overview, selection, findings, and management views.',
    role: 'composition-root',
    files: [
      'viewer/view-controller.mjs',
      'viewer/viewer-actions.js',
      'viewer/viewer-actions-graph.js',
      'viewer/viewer-actions-submaps.js',
      'viewer/viewer-actions-settings.js',
      'viewer/viewer-feedback.js',
      'viewer/viewer-findings.js',
      'viewer/viewer-init.js',
      'viewer/viewer-interaction-actions.mjs',
      'viewer/viewer-interaction-contracts.mjs',
      'viewer/viewer-interaction-context-menu.mjs',
      'viewer/viewer-interaction-document.mjs',
      'viewer/viewer-interaction-filters.mjs',
      'viewer/viewer-interaction-navigation.mjs',
      'viewer/viewer-interaction-pointer.mjs',
      'viewer/viewer-interaction-selection.mjs',
      'viewer/viewer-interaction-shortcuts.mjs',
      'viewer/viewer-interaction-submaps.mjs',
      'viewer/viewer-interactions.mjs',
      'viewer/viewer-module-stats.js',
      'viewer/viewer-overview.js',
      'viewer/viewer-popover.js',
      'viewer/viewer-selection-detail.js',
      'viewer/viewer-selection-quality.js',
      'viewer/viewer-selection-summary.js',
      'viewer/viewer-selection.js',
      'viewer/viewer-subgraph-selection.js',
      'viewer/viewer-submap-edit-state.js',
      'viewer/viewer-submap-availability.js',
      'viewer/viewer-submap-preview.js',
      'viewer/viewer-submap-revisions.js',
      'viewer/viewer-settings-renderer.js',
      'viewer/viewer-submaps.js',
      'viewer/viewer-viewport.js'
    ],
    contracts: ['ViewerStore', 'ViewController', 'ViewerUiController', 'GraphGateway'],
    compositionRoot: true,
    design: designStatus('pass', 'pass', 'pass', 'pass', 'pass'),
    decision: 'Keep viewer-init as the composition root and inject browser capabilities into the UI controller.'
  }
]
