export { createDetectionFiles } from '#core/detection-files.mjs'
export { createStackDetectorRegistry } from '#core/detection-stacks.mjs'
export { detectSourceRoots, detectAliases, detectModules, detectFrontend } from '#core/detection-structure.mjs'
export { detectLayers, detectBackend } from '#core/detection-presets.mjs'
export { detectProject, detect, detectSummary } from '#core/detection-project.mjs'
